web_app/idiotsolutions/config/routes.rb
Rails.application.routes.draw do
  get 'fire_system/index'

  get 'location/index'

  get 'home_page/index'

  get 'meeting_rooms_status', to: 'meeting_rooms#status', as: 'meeting_rooms_status'
  match 'meeting_rooms_analytics', to: 'meeting_rooms#analytics', as: 'meeting_rooms_analytics', via: [:get, :post]

  post 'reservations', to: 'reservations#index', as: 'reservations_index'

  resources :reservations
  resources :meeting_rooms
  resources :employees
  root 'home_page#index'
end

web_app/idiotsolutions/app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :employee
  belongs_to :meeting_room
  enum status: [:available, :occupied, :unused]

  def self.total_on(id)
  	where(meeting_room_id: id).count
  end

  def durations_and_count(reservations)
  	reservations.each do |r|
  		# r.time -
  	end
  end
end

web_app/idiotsolutions/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @date = params[:date] || Date.today
    @reservations = Reservation.where(reservation_date: @date).order(created_at: :asc)
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:reservation_date, :time_start, :time_end, :purpose, :no_of_participants, :employee_id, :meeting_room_id)
    end
end

web_app/idiotsolutions/app/helpers/reservations_helper.rb
module ReservationsHelper
end

web_app/idiotsolutions/app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reservation_date %><br>
    <%= f.date_select :reservation_date %>
  </div>
  <div class="field">
    <%= f.label :time_start %><br>
    <%= f.time_select :time_start %>
  </div>
  <div class="field">
    <%= f.label :time_end %><br>
    <%= f.time_select :time_end %>
  </div>
  <div class="field">
    <%= f.label :purpose %><br>
    <%= f.text_field :purpose %>
  </div>
  <div class="field">
    <%= f.label :no_of_participants %><br>
    <%= f.number_field :no_of_participants %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.text_field :employee_id %>
  </div>
  <div class="field">
    <%= f.label :meeting_room_id %><br>
    <%= f.text_field :meeting_room_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

web_app/idiotsolutions/app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

web_app/idiotsolutions/app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reservations</h1>

<div class="res-pagination">
  <button class="page-link" href="#" aria-label="Previous">
    <span aria-hidden="true">&laquo;</span>
    <span class="sr-only">Previous</span>
  </button>
  <%= form_tag reservations_index_path, style: "margin-left:1em; margin-right:1em; display:inline-block" do %>
    <%= date_field_tag :date, @date, onchange: "this.form.submit();" %>
  <% end %>
  <button class="page-link" href="#" aria-label="Next">
    <span aria-hidden="true">&raquo;</span>
    <span class="sr-only">Next</span>
  </button>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Reservation date</th>
      <th>Time start</th>
      <th>Time end</th>
      <th>Purpose</th>
      <th>No of participants</th>
      <th>Employee</th>
      <th>Meeting room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.reservation_date %></td>
        <td><%= reservation.time_start.strftime("%I:%M%p")  %></td>
        <td><%= reservation.time_end.strftime("%I:%M%p") %></td>
        <td><%= reservation.purpose %></td>
        <td><%= reservation.no_of_participants %></td>
        <td><%= reservation.employee.first_name + " " + reservation.employee.last_name %></td>
        <td><%= reservation.meeting_room.room %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Reservation', new_reservation_path %>

web_app/idiotsolutions/app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

web_app/idiotsolutions/app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reservation date:</strong>
  <%= @reservation.reservation_date %>
</p>

<p>
  <strong>Time start:</strong>
  <%= @reservation.time_start %>
</p>

<p>
  <strong>Time end:</strong>
  <%= @reservation.time_end %>
</p>
<p>
  <strong>Status:</strong>
  <%= @reservation.status %>
</p>
<p>
  <strong>Purpose:</strong>
  <%= @reservation.purpose %>
</p>

<p>
  <strong>No of participants:</strong>
  <%= @reservation.no_of_participants %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @reservation.employee.first_name + " " + @reservation.employee.last_name %>
</p>

<p>
  <strong>Meeting room:</strong>
  <%= @reservation.meeting_room %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>