web_app/idiotsolutions/config/routes.rb
Rails.application.routes.draw do
  get 'fire_system/index'

  get 'location/index'

  get 'home_page/index'

  get 'meeting_rooms_status', to: 'meeting_rooms#status', as: 'meeting_rooms_status'
  match 'meeting_rooms_analytics', to: 'meeting_rooms#analytics', as: 'meeting_rooms_analytics', via: [:get, :post]

  post 'reservations', to: 'reservations#index', as: 'reservations_index'

  resources :reservations
  resources :meeting_rooms
  resources :employees
  root 'home_page#index'
end

web_app/idiotsolutions/app/models/meeting_room.rb
class MeetingRoom < ActiveRecord::Base
  belongs_to :employee
  belongs_to :equipment
end

web_app/idiotsolutions/app/controllers/meeting_rooms_controller.rb
class MeetingRoomsController < ApplicationController
  before_action :set_meeting_room, only: [:show, :edit, :update, :destroy]

  # GET /meeting_rooms
  # GET /meeting_rooms.json
  def analytics
    @date = Hash.new
    # @time = Hash.new
    @date['from'] = params[:date_from] || (Date.today - 3.day).strftime("%F")
    @date['to'] = params[:date_to] || (Date.today + 3.day).strftime("%F")
    # @time['from'] = params[:time_from] || Time.now.to_s(:time)
    # @time['to'] = params[:time_to] || Time.now.to_s(:time)

  end
  
  def status
    @meeting_rooms = MeetingRoom.all
  end

  def index
    @meeting_rooms = MeetingRoom.all
  end

  # GET /meeting_rooms/1
  # GET /meeting_rooms/1.json
  def show
  end

  # GET /meeting_rooms/new
  def new
    @meeting_room = MeetingRoom.new
  end

  # GET /meeting_rooms/1/edit
  def edit
  end

  # POST /meeting_rooms
  # POST /meeting_rooms.json
  def create
    @meeting_room = MeetingRoom.new(meeting_room_params)

    respond_to do |format|
      if @meeting_room.save
        format.html { redirect_to @meeting_room, notice: 'Meeting room was successfully created.' }
        format.json { render :show, status: :created, location: @meeting_room }
      else
        format.html { render :new }
        format.json { render json: @meeting_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meeting_rooms/1
  # PATCH/PUT /meeting_rooms/1.json
  def update
    respond_to do |format|
      if @meeting_room.update(meeting_room_params)
        format.html { redirect_to @meeting_room, notice: 'Meeting room was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting_room }
      else
        format.html { render :edit }
        format.json { render json: @meeting_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meeting_rooms/1
  # DELETE /meeting_rooms/1.json
  def destroy
    @meeting_room.destroy
    respond_to do |format|
      format.html { redirect_to meeting_rooms_url, notice: 'Meeting room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting_room
      @meeting_room = MeetingRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_room_params
      params.require(:meeting_room).permit(:reservation_date, :room, :area, :time_start, :time_end, :purpose, :equipment, :no_of_participants, :no_of_participants, :capacity, :employee_id, :status)
    end
end

web_app/idiotsolutions/app/helpers/meeting_rooms_helper.rb
module MeetingRoomsHelper
end

web_app/idiotsolutions/app/views/meeting_rooms/_analytics_filterA.html.erb
<div class="row filter">
	<div class="panel-group">
		<div class="panel panel-default">
		  <div class="panel-heading">Scope</div>
		  <div class="panel-body">
		    Date <br>
		    <div style="padding-left:1em">
		    <label>From: <%= date_field_tag :date_from, '', class: 'pull-right' %></label><br>
		    <label>To: <%= date_field_tag :date_to, '', class: 'pull-right' %></label><br>
		    </div><br>
		    Time <br>
		    <div style="padding-left:1em">
		    From: <%= time_field_tag :time_from %>
		    To: <%= time_field_tag :time_to %>
		    </div>
		  </div>
		</div>
		<div class="panel panel-default">
		  <div class="panel-heading">Filters</div>
		  <ul class="panel-body" style="list-style:none">
		    <li><label><input type="checkbox" value="false_reserve" checked="checked"> Unused</label></li>
		    <li><label><input type="checkbox" value="pk_reserve" checked="checked"> Peak Hours</label></li>
		    <li><label><input type="checkbox" value="wi_reserve" checked="checked"> Walk-ins</label></li>
		    <li><label><input type="checkbox" value="canc_reserve" checked="checked"> Cancelled</label></li>
		    <li><label><input type="checkbox" value="room_usage" checked="checked"> Room Usage</label></li>
		  </ul>
		</div>
	</div>
</div>

web_app/idiotsolutions/app/views/meeting_rooms/_analytics_filterB.html.erb
<%= form_tag meeting_rooms_analytics_path, class: "row filter" do %>
	Date: <%= date_field_tag :date_from, date_from %> to <%= date_field_tag :date_to, date_to %>
	<%= submit_tag "Apply Filter" %>
<% end %>

web_app/idiotsolutions/app/views/meeting_rooms/_form.html.erb
<%= form_for(@meeting_room) do |f| %>
  <% if @meeting_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting_room.errors.count, "error") %> prohibited this meeting_room from being saved:</h2>

      <ul>
      <% @meeting_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room %><br>
    <%= f.text_field :room %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :equipment %><br>
    <%= f.number_field :equipment %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

web_app/idiotsolutions/app/views/meeting_rooms/analytics.html.erb
<script type="text/javascript">
	<% date_range = (@date['from']..@date['to']).map{|d| d} %>
	$(function(){
		new Highcharts.Chart({
			chart: {
				renderTo: "main_chart"
			},
			title: {
            text: 'Meeting Room Reservations Analytics'
	        },
	        xAxis: {
	            categories: <%= raw date_range %>
	        },
	        series: [
		        {
		            type: 'column',
		            name: "Total Reservations",
		            data: <%= reservations_arr = date_range.map {|date| Reservation.where(reservation_date: date).count} %>
		        },
		        {
		            type: 'column',
		            name: "Total Reservers",
		            data: <%= date_range.map {|date| Reservation.where(reservation_date: date).select(:employee_id).distinct.count} %>
		        },
		        {
		            type: 'spline',
		            name: "Total Misused Reservations",
		            data: <%= misused_reservations_arr = date_range.map {|date| Reservation.where(reservation_date: date, status: 2).count} %>
		        }
		    ]
		});

		new Highcharts.Chart({
	        chart: {
	            type: 'pie',
	            renderTo: 'pie_chart'
	        },
	        title: {
	            text: ''
	        },
	        subtitle: {
	            text: 'Click the slices to view reserving time counts.'
	        },
	        plotOptions: {
	            series: {
	                dataLabels: {
	                    enabled: true,
	                    format: '{point.name}: {point.y:.1f}%'
	                }
	            }
	        },

	        tooltip: {
	            headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
	            pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}%</b> of total<br/>'
	        },
	        series: [{
	            name: 'Meeting Rooms',
	            colorByPoint: true,
	            data: [
	            <% meeting_room_reserve = Hash.new %>
	            <% meeting_rooms = MeetingRoom.all %>
	            <% meeting_rooms.each do |mr| %>
	            {
	                name: '<%= mr.room %>',
	                y: <%= reserved_count = Reservation.where(reservation_date: (@date['from']..@date['to']), meeting_room_id: mr.id).count %>,
	                drilldown: <%= mr.id %>
	                <% meeting_room_reserve[mr.room] = reserved_count %>
	            }, 
	            <% end -%>
	            ]
	        }],
	        drilldown: {
	            series: [
	            <% meeting_rooms.each do |mr| %>
	            {
	                name: '<%= mr.room %>',
	                id: <%= mr.id %>,
					<% Reservation.where(reservation_date: (@date['from']..@date['to']), meeting_room_id: mr.id) %>
	                data: [
	                    ['1 hour', <%= Reservation.where(reservation_date: (@date['from']..@date['to']), meeting_room_id: mr.id).count %>]
	                ]
	            }, 
	            <% end -%>
	            ]
	        }
	    });
	});
</script>

<h1>Meeting Room Reservation Analytics</h1>
<%#= Reservation.where(reservation_date: (@date['from']..@date['to']), meeting_room_id: 1).group %>,
<%#= Reservation.where(reservation_date: (@date['from']..@date['to']), meeting_room_id: 1).map {|r| (r.time_end - r.time_start)} %>

<%#= @date['from'].year %>
<%#= Date.strptime(@date['from'], '%Y-%m-%d')..Date.strptime(@date['to'], '%Y-%m-%d') %>
<%# ((Date.new(@date['from'].year,@date['from'].month,@date['from'].day))..(Date.new(@date['to'].year,@date['to'].month,@date['to'].day))).each do |d| %>
<%#= (@date['from']..@date['to']).map{|date| date.strftime("%b %d")} %>
<%#= (@date['from']..@date['to']).map{|d| d.strftime("%F")} %>
<%#= d %>
<%# end -%>
<%= render partial: "analytics_filterB", locals: {date_from: @date['from'], date_to: @date['to']} %>

<!-- <div class="row summary">
	<button><span class="glyphicon glyphicon-triangle-top"></span> Summary </button>
	<div class="details">
		<ul style="list-style:none">
		    <li>Total Number of False/Unused Reservations:  45</li>
		    <li>B:</li>
		    <li>C:</li>
		    <li>D:</li>
		    <li>E:</li>
		</ul>
	</div>
</div> -->

<div class="row chart-view">

	<div class="chart-card-item">
		<div class="card">
		  <div class="panel panel-primary">
		  	<div class="panel-heading"> Room Usage</div>
		    <div class="panel-body" id="main_chart"></div>
			<div class="panel-footer">
				<div class="row">
					<div class="col-xs-4" style="background:white">
						<br>SUMMARY<br><br>
						<ul style="list-style:none;"> 
							<li>Total Number of False/Unused Reservations: 
								<font color="blue"><%= misused_reservations_arr.sum() %></font>
							</li>
							<li>Total Number of Reservations: 
								<font color="blue"><%= reservations_arr.sum() %></font>
							</li>
							<li>Favorite Meeting Room: 
								<font color="blue"><%= meeting_room_reserve.max_by{|k,v| v}[0] %></font>
							</li>
							<li>Most hated Meeting Room: 
								<font color="blue"><%= meeting_room_reserve.min_by{|k,v| v}[0] %></font>
							</li>
							<li>Top Reserver: 
								<% emp_id = Reservation.where(reservation_date: (@date['from']..@date['to'])).group(:employee_id).order('count_id DESC').limit(1).count(:id).keys[0] %>
								<font color="blue"><%= Employee.find(emp_id).first_name %> <%= Employee.find(emp_id).last_name %></font>
							</li>
							<li>Bargains without Reservation: 
								<font color="blue">35</font>
							</li>
							<li>Top Reservation Duration:  
								<font color="blue">1 hour</font>
							</li>
						</ul>
					</div>
					<div class="col-xs-8">
						<div id="pie_chart"></div>
					</div>
				</div>
			</div>
		  </div>
		</div>
	</div>

</div>

web_app/idiotsolutions/app/views/meeting_rooms/edit.html.erb
<h1>Editing Meeting Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting_room %> |
<%= link_to 'Back', meeting_rooms_path %>

web_app/idiotsolutions/app/views/meeting_rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meeting Rooms</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Room</th>
      <th>Area</th>
      <th>Equipment</th>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meeting_rooms.each do |meeting_room| %>
      <tr>
        <td><%= meeting_room.room %></td>
        <td><%= meeting_room.area %></td>
        <td><%= meeting_room.equipment.resources %></td>
        <td><%= meeting_room.capacity %></td>
        <td><%= link_to 'Show', meeting_room %></td>
        <td><%= link_to 'Edit', edit_meeting_room_path(meeting_room) %></td>
        <td><%= link_to 'Destroy', meeting_room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting room', new_meeting_room_path %>

web_app/idiotsolutions/app/views/meeting_rooms/new.html.erb
<h1>New Meeting Room</h1>

<%= render 'form' %>

<%= link_to 'Back', meeting_rooms_path %>

web_app/idiotsolutions/app/views/meeting_rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @meeting_room.room %>
</p>

<p>
  <strong>Area:</strong>
  <%= @meeting_room.area %>
</p>

<p>
  <strong>Equipment:</strong>
  <%= @meeting_room.equipment.resources %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @meeting_room.capacity %>
</p>

<%= link_to 'Edit', edit_meeting_room_path(@meeting_room) %> |
<%= link_to 'Back', meeting_rooms_path %>

web_app/idiotsolutions/app/views/meeting_rooms/status.html.erb
<p id="notice"><%= notice %></p>

<h1>Meeting Room Status</h1>
Date:<font color="blue"><%= @date = Date.today %></font><br>
Time:<font color="blue"><%= @time = Time.now.to_s(:time) %></font><br>
<!-- Time:<font color="blue"><%#= @time = Time.new(2016,8,3,10,0,0).to_s(:time) %></font><br> -->

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Room</th>
      <th>Area</th>
      <th>Equipment</th>
      <th>Capacity</th>
      <th>Floor</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @meeting_rooms.each do |meeting_room| %>
      <tr>
        <td><%= meeting_room.room %></td>
        <td><%= meeting_room.area %></td>
        <td><%= meeting_room.equipment.resources %></td>
        <td><%= meeting_room.capacity %></td>
        <td><%= meeting_room.floor %></td>
        <% @reservation = Reservation.where(reservation_date: @date).where("time_start <= ?", @time).where("time_end >= ?", @time) %>
        <% if @reservation.exists?(meeting_room_id: meeting_room.id) %>
          <% @reserve = @reservation.where(meeting_room_id: meeting_room.id) %>
          <% @reserve.each do |r| %>
            <% if ((r.time_start - 15.minutes).to_s(:time) <= @time) %>
              <td>occupied</td>
            <% else %>
              <td><%= r.status %></td>
            <% end %>
          <% end %>
        <% else %>
          <% @reserve = Reservation.where(meeting_room_id: meeting_room.id, reservation_date: nil) %>
          <% @reserve.each do |r| %>
            <td><%= r.status %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>