web_app/idiotsolutions/config/routes.rb
Rails.application.routes.draw do
  get 'fire_system/index'

  get 'location/index'

  get 'home_page/index'

  get 'meeting_rooms_status', to: 'meeting_rooms#status', as: 'meeting_rooms_status'
  match 'meeting_rooms_analytics', to: 'meeting_rooms#analytics', as: 'meeting_rooms_analytics', via: [:get, :post]

  post 'reservations', to: 'reservations#index', as: 'reservations_index'

  resources :reservations
  resources :meeting_rooms
  resources :employees
  root 'home_page#index'
end

web_app/idiotsolutions/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "idIOT Solutions", root_path, class: "navbar-brand" %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <!-- <li class="active"><a href="#">Home</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li> -->
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Meeting Rooms <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Show All", meeting_rooms_status_path %></li>
                  <li role="separator" class="divider"></li>
                  <!-- <li class="dropdown-header">Reservation</li> -->
                  <li><%= link_to "Reservations", reservations_path %></li>
                  <li><%= link_to "New Reservation", new_reservation_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Analytics", meeting_rooms_analytics_path %></li>
                </ul>
              </li>
              <li><%= link_to "Fire System", fire_system_index_path %></li>
              <li><%= link_to "Locator", location_index_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

web_app/idiotsolutions/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>idIOT Solutions</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "jsapi", "highcharts", "drilldown" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if controller.controller_name == 'home_page' %>
	<%= yield %>
<% else %>

<div class="container">
	<%= render 'layouts/header' %>
	<%= yield %>
</div>

<% end %>

</body>
</html>